model:
  base_learning_rate: 1.0e-4
  target: modules.diffusion.DiffusionEngine
  params:
    use_ema: True
    ema_decay_rate: 0.9999
    ema_update_every: 400
    # input_key: ltnt
    
    # ema_config:
    #   target: modules.lit_ema_cpu.LitEmaCPU
    #   params:
    #     update_every: 6

    denoiser_config:
      target: sgm.modules.diffusionmodules.denoiser.Denoiser
      params:
        scaling_config:
          target: sgm.modules.diffusionmodules.denoiser_scaling.EDMScaling
          params:
            sigma_data: 0.5

    network_config:
      target: modules.models.decoding.openai_decoder.DiffusionDecoder
      params:
        model_channels: 320
        dropout: 0.0
        use_checkpoint: True
        use_scale_shift_norm: True

    conditioner_config:
      target: diffusion_decoder.LatentConditioner
      params:
        scale_factor: 0.13025
        emb_models:
          - is_trainable: True
            input_key: ltnt
            ucg_rate: 0.2
            target: sgm.modules.encoders.modules.IdentityEncoder
            
    first_stage_config:
      target: sgm.models.autoencoder.IdentityFirstStage

    loss_fn_config:
      target: sgm.modules.diffusionmodules.loss.StandardDiffusionLoss
      params:
        loss_weighting_config:
          target: sgm.modules.diffusionmodules.loss_weighting.EDMWeighting
          params:
            sigma_data: 0.5
        sigma_sampler_config:
          target: sgm.modules.diffusionmodules.sigma_sampling.EDMSampling


    sampler_config:
      target: sgm.modules.diffusionmodules.sampling.EulerEDMSampler
      params:
        num_steps: 25

        discretization_config:
          target: sgm.modules.diffusionmodules.discretizer.EDMDiscretization

        guider_config:
          target: sgm.modules.diffusionmodules.guiders.IdentityGuider
    #     guider_config:
    #       target: sgm.modules.diffusionmodules.guiders.IdentityGuider
    #       # params:
    #       #   scale: 2.0